version: '3.2'
services:
  soswebsite:
    image: wordpress:5.2.2-apache
    hostname: soswebsite
    networks:
      - proxy    
    volumes:
      - /data/soswebsite/sos:/var/www/html
    ports:
      - 25223:80
    depends_on:
      - db_mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  soswebmap:
    image: terrabrasilis/webmap:prod_v2.1.9
    hostname: soswebmap
    networks:
      - proxy
    ports:
      - "80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  ### Business API as a Service
  sosbusiness-api:
    image: terrabrasilis/business-api:v1.2.1
    hostname: "sosbusiness.api"
    networks:
      - proxy
    ports:
      - "13333:8090"
    environment:   
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - sosmongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # The instance of MongoDB to store the BusinessAPI documents
  sosmongodb:
    image: mongo:4.4
    hostname: "sosmongo.db"
    networks:
      - proxy
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - /data/sosmongodb:/data/db
    ports:
      - "30100:27017"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
