# A compose docker used to deploy the TerraAmazon-Monitor App
version: "2"
services:
  app-monitor-bookmark:
    image: terrabrasilis/ta-monitor:v1.0.0
    container_name: app-monitor-bookmark
    ports:
      - "81:36003"
      - "82:36004"
    volumes:
      - /data/monitor/app/monitor-bookmark:/data
    restart: always

  app-monitor-updated:
    image: terrabrasilis/ta-monitor:v1.0.0
    container_name: app-monitor-updated
    ports:
      - "83:36005"
    volumes:
      - /data/monitor/app/monitor_updated:/data
    restart: always

  geoserver-monitor:
    image: terrabrasilis/geoserver-monitor:v2.11
    container_name: geoserver-monitor
    ports:
      - "8181:8080"
    volumes:
      - /data/monitor/geoserver/data_dir:/opt/geoserver/data_dir
      - ${PWD}/geoserver_setenv.sh:/usr/local/tomcat/bin/setenv.sh
    environment:
      - "GEOSERVER_URL=/geoserver"
      - "GEOSERVER_DATA_DIR=/opt/geoserver/data_dir"
    restart: always

