version: '2'
services:

  ### Business API as a Service
  business-api:
    image: terrabrasilis/business-api:v1.2
    hostname: "business.api"
    ports:
      # the 8090 port is configured inside application terrabrasilis-business-api/src/main/resources/application.properties
      - "2222:8090"
    environment:   
      - "SPRING_PROFILES_ACTIVE=docker"
    links:
      - mongodb
    restart: always

  # The instance of MongoDB to store the BusinessAPI documents
  mongodb:
    image: mongo:4
    hostname: "mongo.db"
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      #MONGO_INITDB_DATABASE: businessapi
      #MONGO_INITDB_ROOT_USERNAME: business-api
      #MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      # Use your path to map one volume
      - /home/andre/Dados/tmp/mongodb:/data/db
    ports:
      # the 27018 port is exposed to avoid conflict with some mongo localhost instance.
      - "27018:27017"
    restart: always