version: '3.2'
services:
  amsh-webapp:
    image: terrabrasilis/ams-webapp:v2.0.6.risk_features.rc
    hostname: amsh.webapp
    entrypoint: /docker-entrypoint.sh
    networks:
      - proxy
    ports:
      - 7000
    environment:
      - "SCRIPT_NAME=/ams-homologation"
      - "GEOSERVER_URL=http://terrabrasilis.dpi.inpe.br/geoserver"
      - "SERVER_NAME=terrabrasilis.dpi.inpe.br"
      - "APPLICATION_ROOT=/ams-homologation/"
      - "DB_AMAZON_URL=/run/secrets/ams4h.database.url"
      - "DB_CERRADO_URL=/run/secrets/ces2.database.url"
    secrets:
      - ams4h.database.url
      - ces2.database.url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # Amazon Database Update Task
  ams4h-sync:
    image: terrabrasilis/ams-sync:v2.0.6.risk_features.rc
    hostname: ams4h.sync
    networks:
      - proxy
    volumes:
      - /data/ams4h/sync:/usr/local/data
    environment:
      - "BIOME=Amazônia"
      - "INPUT_GEOTIFF_FUNDIARY_STRUCTURE=estrutura_fundiaria_cst_2023.tif"
      - "DATABASE_URL=/run/secrets/ams4h.database.url"
      - "ALL_DATA=True"
      - "FTP_HOST=/run/secrets/risk.ftp.host"
      - "FTP_PORT=/run/secrets/risk.ftp.port"
      - "FTP_PATH=/run/secrets/risk.ftp.path"
      - "FTP_USER=/run/secrets/risk.ftp.user"
      - "FTP_PASS=/run/secrets/risk.ftp.pass"
      - "RISK_OUTPUT_PATH=/usr/local/data"
    secrets:
      - ams4h.database.url
      - risk.ftp.host
      - risk.ftp.port
      - risk.ftp.path
      - risk.ftp.user
      - risk.ftp.pass
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  ams4h.database.url:
    external: true
  ces2.database.url:
    external: true
  risk.ftp.host:
    external: true
  risk.ftp.port:
    external: true
  risk.ftp.path:
    external: true
  risk.ftp.user:
    external: true
  risk.ftp.pass:
    external: true
    
networks:
  proxy:
    external: true
