version: '3.2'
services:
  ams-webapp-homolog:
    image: terrabrasilis/ams-webapp:v1.3.1.homologation
    hostname: ams.webapp.homologation
    entrypoint: /docker-entrypoint.sh
    networks:
      - proxy
    ports:
      - 80:7000
    environment:
      - "HOMOLOGATION=True"
      - "SCRIPT_NAME=/ams-homologation"
      - "GEOSERVER_URL=http://terrabrasilis.dpi.inpe.br/geoserver"
      - "SERVER_NAME=terrabrasilis.dpi.inpe.br"
      - "APPLICATION_ROOT=/ams-homologation/"
      - "DETER_DAILY_UPDATE_TIME=6:30"
    secrets:
      - deter.database.url
      - ams.database.url
    environment:
      DETER_DATABASE_URL: /run/secrets/deter.database.url
      DATABASE_URL: /run/secrets/ams.database.url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  deter.database.url:
    external: true
  ams.database.url:
    external: true

networks:
  proxy:
    external: true
