version: '3.2'
services:
  amsh-webapp:
    image: terrabrasilis/ams-webapp:v1.6.1
    hostname: amsh.webapp
    entrypoint: /docker-entrypoint.sh
    networks:
      - proxy
    ports:
      - 7000
    environment:
      - "SCRIPT_NAME=/ams-homologation"
      - "GEOSERVER_URL=http://terrabrasilis.dpi.inpe.br/geoserver"
      - "SERVER_NAME=terrabrasilis.dpi.inpe.br"
      - "APPLICATION_ROOT=/ams-homologation/"
      - "DB_AMAZON_URL=/run/secrets/ams2h.database.url"
      - "DB_CERRADO_URL=/run/secrets/cesh.database.url"
    secrets:
      - ams2h.database.url
      - cesh.database.url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # Amazon Database Update Task
  ams2h-sync:
    image: terrabrasilis/ams-sync:v1.5.8
    hostname: ams2h.sync
    networks:
      - proxy
    volumes:
      - /data/ams2h/sync:/usr/local/data
    environment:
      - "BIOME='Amazônia'"
      - "INPUT_GEOTIFF_FUNDIARY_STRUCTURE=estrutura_fundiaria_cst_2022.tif"
      - "DATABASE_URL=/run/secrets/ams2h.database.url"
      - "ALL_DATA=False"
    secrets:
      - ams2h.database.url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # Cerrado Database Update Task
  cesh-sync:
    image: terrabrasilis/ams-sync:v1.6.1.land_use_selector.rc
    hostname: cesh.sync
    networks:
      - proxy
    volumes:
      - /data/cesh/sync:/usr/local/data
    environment:
      - "BIOME='Cerrado'"
      - "INPUT_GEOTIFF_FUNDIARY_STRUCTURE=estrutura_fundiaria_cerrado_cst_lzw.tif"
      - "DATABASE_URL=/run/secrets/cesh.database.url"
      - "ALL_DATA=False"
    secrets:
      - cesh.database.url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  ams2h.database.url:
    external: true
  cesh.database.url:
    external: true
    
networks:
  proxy:
    external: true
