version: '3.2'
services:
  amsh-webapp:
    image: terrabrasilis/ams-webapp:v1.4.2.rc
    hostname: amsh.webapp
    entrypoint: /docker-entrypoint.sh
    networks:
      - proxy
    ports:
      - 7000
    environment:
      - "SCRIPT_NAME=/ams-homologation"
      - "GEOSERVER_URL=http://terrabrasilis.dpi.inpe.br/geoserver"
      - "SERVER_NAME=terrabrasilis.dpi.inpe.br"
      - "APPLICATION_ROOT=/ams-homologation/"
      - "DATABASE_URL=/run/secrets/amst.database.url"
    secrets:
      - amst.database.url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # task used to copy deter and focuses data to ams database and process the spatial unit statistics
  amst-sync:
    image: terrabrasilis/ams-sync:v1.4.2.rc
    hostname: amst.sync
    networks:
      - proxy
    volumes:
      - /data/amst/sync:/usr/local/data
    environment:
      - "INPUT_GEOTIFF_FUNDIARY_STRUCTURE=estrutura_fundiaria_cst_2022.tif"
      - "DATABASE_URL=/run/secrets/amst.database.url"
    secrets:
      - amst.database.url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  deter.database.url:
    external: true
  amst.database.url:
    external: true

networks:
  proxy:
    external: true
