version: '3.2'
services:
  ams-webapp:
    image: terrabrasilis/ams-webapp:v1.6.5
    hostname: ams.webapp
    entrypoint: /docker-entrypoint.sh
    networks:
      - proxy
    ports:
      - 7000
    environment:
      - "SCRIPT_NAME=/ams"
      - "GEOSERVER_URL=http://terrabrasilis.dpi.inpe.br/geoserver"
      - "SERVER_NAME=terrabrasilis.dpi.inpe.br"
      - "APPLICATION_ROOT=/ams/"
      - "DB_AMAZON_URL=/run/secrets/ams3.database.url"
      - "DB_CERRADO_URL=/run/secrets/ces2.database.url"
    secrets:
      - ams3.database.url
      - ces2.database.url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  ams3.database.url:
    external: true
  ces2.database.url:
    external: true

networks:
  proxy:
    external: true
