version: '3.2'
services:
  ams-webapp:
    image: terrabrasilis/ams-webapp:v1.6.5
    hostname: ams.webapp
    entrypoint: /docker-entrypoint.sh
    networks:
      - proxy
    ports:
      - 7000
    environment:
      - "SCRIPT_NAME=/ams"
      - "GEOSERVER_URL=http://terrabrasilis.dpi.inpe.br/geoserver"
      - "SERVER_NAME=terrabrasilis.dpi.inpe.br"
      - "APPLICATION_ROOT=/ams/"
      - "DB_AMAZON_URL=/run/secrets/ams3.database.url"
      - "DB_CERRADO_URL=/run/secrets/ces2.database.url"
    secrets:
      - ams3.database.url
      - ces2.database.url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # Amazon Database Update Task
  ams3-sync:
    image: terrabrasilis/ams-sync:v1.6.4
    hostname: ams3.sync
    networks:
      - proxy
    volumes:
      - /data/ams2/sync:/usr/local/data
    environment:
      - "BIOME='Amazônia'"
      - "INPUT_GEOTIFF_FUNDIARY_STRUCTURE=estrutura_fundiaria_cst_2023.tif"
      - "DATABASE_URL=/run/secrets/ams3.database.url"
      - "ALL_DATA=True"
    secrets:
      - ams3.database.url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # Cerrado Database Update Task
  ces2-sync:
    image: terrabrasilis/ams-sync:v1.6.4
    hostname: ces2.sync
    networks:
      - proxy
    volumes:
      - /data/ces/sync:/usr/local/data
    environment:
      - "BIOME='Cerrado'"
      - "INPUT_GEOTIFF_FUNDIARY_STRUCTURE=estrutura_fundiaria_cerrado_cst_lzw.tif"
      - "DATABASE_URL=/run/secrets/ces2.database.url"
      - "ALL_DATA=True"
    secrets:
      - ces2.database.url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # Queimadas Database Update Task
  fires-sync:
    image: terrabrasilis/general-fires-data-task-main:v1.1.4
    hostname: fires.sync
    networks:
      - proxy
    volumes:
      - /data/fires/sync:/usr/local/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  ams3.database.url:
    external: true
  ces2.database.url:
    external: true

networks:
  proxy:
    external: true
