version: '3.2'
services:
  ams-webapp:
    image: terrabrasilis/ams-webapp:v1.4.0
    hostname: ams.webapp
    entrypoint: /docker-entrypoint.sh
    networks:
      - proxy
    ports:
      - 7000
    environment:
      - "SCRIPT_NAME=/ams"
      - "GEOSERVER_URL=http://terrabrasilis.dpi.inpe.br/geoserver"
      - "SERVER_NAME=terrabrasilis.dpi.inpe.br"
      - "APPLICATION_ROOT=/ams/"
      - "DATABASE_URL=/run/secrets/ams.database.url"
    secrets:
      - ams.database.url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # task used to copy deter and focuses data to ams database and process the spatial unit statistics
  ams-sync:
    image: terrabrasilis/ams-sync:v1.4.1.rc
    hostname: ams.sync
    networks:
      - proxy
    volumes:
      - /data/ams/sync:/usr/local/data
    environment:
      - "INPUT_GEOTIFF_FUNDIARY_STRUCTURE=estrutura_fundiaria_cst_2022.tif"
      - "DATABASE_URL=/run/secrets/ams.database.url"
    secrets:
      - ams.database.url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # task used to copy focuses from queimadas geoserver to local database
  fires-sync:
    image: terrabrasilis/general-fires-data-task-main:v1.1.2
    hostname: fires.sync
    networks:
      - proxy
    volumes:
      - /data/fires/sync:/usr/local/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  deter.database.url:
    external: true
  ams.database.url:
    external: true

networks:
  proxy:
    external: true
