# Stack name on swarm cluster: webapps 
version: '3.2'
services:
  webmap:
    image: terrabrasilis/webmap:prod_v2.4.1
    hostname: webmap.production
    networks:
      - proxy
    ports:
      - "80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  deforestation-dashboard:
    image: terrabrasilis/deforestation-dashboard:prod_v3.1.2
    hostname: deforestation.dashboard.production
    networks:
      - proxy
    ports:
      - "80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
