version: '3.2'
services:
  terrabrasilis-webapp:
    image: terrabrasilis/terrabrasilis-webapp:v2.5-beta
    hostname: terrabrasilis.webapp
    networks:
      - proxy
    ports:
      - "80"
    volumes:
      - /data/webapp/assets/i18n:/assets/i18n
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
