version: '3.2'
services:
  webmap-homolog:
    image: terrabrasilis/webmap:hom_v2.3.10
    hostname: webmap.homologation
    networks:
      - proxy
    ports:
      - 80
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

  deforestation-dashboard-homolog:
    image: terrabrasilis/deforestation-dashboard:hom_v3.2.0
    hostname: deforestation.dashboard.homologation
    networks:
      - proxy
    ports:
      - 80
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
