version: '3.2'
services:
  webmap-homolog:
    image: terrabrasilis/webmap:v2.1.1
    hostname: webmap.homologation
    networks:
      - proxy
    ports:
      - 2222:80
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

  deforestation-dashboard-homolog:
    image: terrabrasilis/deforestation-dashboard:v2.0.11
    hostname: deforestation.dashboard.homologation
    networks:
      - proxy
    ports:
      - 3333:80
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
