version: '3.2'
services:
  terrabrasilis-webapp-homolog:
    image: terrabrasilis/terrabrasilis-webapp:maps-homologation-v1.0.0
    hostname: terrabrasilis.webapp.homologation
    networks:
      - proxy
    ports:
      - 2222:80
    volumes:
      - /data/webapp-homologation/assets/i18n:/assets/i18n
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
