version: '3.2'
services:
  terrabrasilis-webmap-homolog:
    image: terrabrasilis/webmap:v2.0.7
    hostname: terrabrasilis.webmap.homologation
    networks:
      - proxy
    ports:
      - 2222:80
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.master1==master1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
