# The NGINX stack
version: '3.2'
services:
  nginx-manager:
    image: terrabrasilis/nginx-manager:v1.0
    hostname: nginx.manager
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/log:/var/log/nginx
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nodename==master2
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
