# The NGINX stack
version: '3.2'
services:
  nginx-manager:
    #image: terrabrasilis/nginx-manager:v1.1.0
    image: nginx:1.22-alpine
    hostname: nginx.manager
    networks:
      - proxy
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes: 
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/log:/var/log/nginx
      - /data/nginx/html:/usr/share/nginx/html
      - /data/nginx/base/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nodename==master2
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
