version: '3.4'
services:

  # The instance of MongoDB to store the BusinessAPI documents
  mongodb:
    image: mongo:4.4
    hostname: "mongo.db"
    networks:
      - backend
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - /data/mongodb:/data/db
    ports:
      - "27017"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # The instance of RedisDB to store the Deforestation dashboard documents
  redisdb:
    image: terrabrasilis/redis:v01
    ports:
      - "6379"
    networks:
      - backend
    volumes:
      - /data/redis:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
      start_period: 30s

  # Deforestation dashboard API
  redis-api:
    image: terrabrasilis/redis-api:v1.1.2
    ports:
      - "3000"
    networks:
      - proxy
      - backend
    depends_on:
      - redisdb
    environment:
      - REDIS_HOSTNAME=redisdb
      - REDIS_PORT=6379
      - API_PORT=3000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "httpcode=`curl -s -o /dev/null --head -w \"%{http_code}\" -X GET \"http://localhost:3000/dashboard/api/health\"`; if [ ! $httpcode = \"200\" ]; then exit 1; fi"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Business API as a Service
  business-api:
    image: terrabrasilis/business-api:v1.2.3
    networks:
      - proxy
      - backend
    ports:
      - "8090"
    environment:   
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "httpcode=`curl -s -o /dev/null --head -w \"%{http_code}\" -X GET \"http://localhost:8090/api/v1/layer/health\"`; if [ ! $httpcode = \"200\" ]; then exit 1; fi"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # File delivery service API with authentication
  file_delivery_api:
    image: terrabrasilis/file-delivery:v1.0.5
    hostname: file.delivery.auth
    volumes:
      - /data/deter-auth/generated-files:/data/files:ro
      - /data/deter-auth/logs:/logs
    secrets:
      - jwt.private.key
    environment:
      JWT_SECRET: /run/secrets/jwt.private.key
    networks:
      - proxy
    ports:
      - "9000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "httpcode=`curl -s -o /dev/null --head -w \"%{http_code}\" -X GET \"http://localhost:9000/health\"`; if [ ! $httpcode = \"200\" ]; then exit 1; fi"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
        
  # Middleware authentication service
  oauth_api:
    image: terrabrasilis/terrabrasilis-oauth-api:v1.2.2
    hostname: oauth.api
    volumes:
      - /data/oauth-api/logs:/logs
    secrets:
      - jwt.private.key
    environment:
      JWT_SECRET: /run/secrets/jwt.private.key
    networks:
      - proxy
    ports:
      - "9000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "httpcode=`curl -s -o /dev/null --head -w \"%{http_code}\" -X GET \"http://localhost:9000/health\"`; if [ ! $httpcode = \"200\" ]; then exit 1; fi"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Middleware timeseries service 
  timeseries_ocpu:
    image: terrabrasilis/terrabrasilis-timeseries:v1.0.0
    ports:
      - "8004:8004"
    networks:
      - proxy
    restart: always

secrets:
  jwt.private.key:
    external: true

networks:
  proxy:
    external: true
  backend:
    external: true
