version: '3.4'
services:
  homepage:
    image: wordpress:5.8.2-apache
    hostname: homepage
    networks:
      - proxy
      - backend
    volumes:
      - /data/homepage:/var/www/html
    ports:
      - 80
    depends_on:
      - db_mysql
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
  backend:
    external: true
