version: '3.4'
services:
  geonetwork:
    image: terrabrasilis/geonetwork:v3.4.4
    restart: always
    networks:
      - proxy
    ports:
      - "8080"
    environment:
      DATA_DIR: /var/lib/geonetwork_data
    volumes:
      - /data/geonetwork_34:/var/lib/geonetwork_data
      - /data/geonetwork_34/gn.h2.db:/usr/local/tomcat/webapps/gn.h2.db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  proxy:
    external: true
