version: '3.4'

services:

  db_mysql:
    image: mysql:5.7
    volumes:
      - /data/mysql:/var/lib/mysql
    secrets:
      - server.user.mysql
      - server.pass.mysql
      - server.rootpass.mysql
      - server.dbname.mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/server.rootpass.mysql
      MYSQL_DATABASE_FILE: /run/secrets/server.dbname.mysql
      MYSQL_USER_FILE: /run/secrets/server.user.mysql
      MYSQL_PASSWORD_FILE: /run/secrets/server.pass.mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks: 
      - backend

secrets:
  server.user.mysql:
    external: true
  server.pass.mysql:
    external: true
  server.dbname.mysql:
    external: true
  server.rootpass.mysql:
    external: true

networks: 
  backend:
    external: true