# Used for deploy homologation Apps
version: '3.4'

services:

 amsh-webapp:
    image: terrabrasilis/ams-sync:v2.1.0.risk_features.rc
    hostname: amsh.webapp
    entrypoint: /docker-entrypoint.sh
    networks:
      - proxy
    ports:
      - 7000
    environment:
      - "SCRIPT_NAME=/ams-homologation"
      - "GEOSERVER_URL=https://terrabrasilis.dpi.inpe.br/geoserver"
      - "SERVER_NAME=terrabrasilis.dpi.inpe.br"
      - "APPLICATION_ROOT=/ams-homologation/"
      - "DB_AMAZON_URL=/run/secrets/ams4h.database.url"
      - "DB_CERRADO_URL=/run/secrets/ces2h.database.url"
    secrets:
      - ams4h.database.url
      - ces2h.database.url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  ams4h.database.url:
    external: true
  ces2h.database.url:
    external: true

networks:
  proxy:
    external: true
