version: '3.4'
services:
  webmap:
    image: terrabrasilis/webmap:prod_v2.3.0
    hostname: webmap.production
    networks:
      - proxy
    ports:
      - "80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  deforestation-dashboard:
    image: terrabrasilis/deforestation-dashboard:prod_v2.0.19
    hostname: deforestation.dashboard.production
    networks:
      - proxy
    ports:
      - "80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  focuses-of-fires:
    image: terrabrasilis/focuses-of-fires-dashboard:v1.2.3
    networks:
      - proxy
    ports:
      - "80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  cerrado-alert-daily:
    image: terrabrasilis/cerrado-alert-daily:v2.7.5
    networks:
      - proxy
    ports:
      - "80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  cerrado-alert-aggregated:
    image: terrabrasilis/cerrado-alert-aggregated:v2.7.5
    networks:
      - proxy
    ports:
      - "80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  amazon-alert-aggregated:
    image: terrabrasilis/amazon-alert-aggregated:v2.9.4
    networks:
      - proxy
    ports:
      - "80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  amazon-alert-daily:
    image: terrabrasilis/amazon-alert-daily:v2.9.4
    networks:
      - proxy
    ports:
      - "80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
