# Used for deploy manager Apps
version: '3.4'

services:

  pgadmin4:
  # https://hub.docker.com/r/dpage/pgadmin4/
  # https://github.com/postgres/pgadmin4
    image: dpage/pgadmin4:8.5
    ports:
      - 5555:80
    #environment:
      # after starting for the first time, use the web app to change this password
      # and then remove these entries.
      # the initial email
      #- "PGADMIN_DEFAULT_EMAIL=<an_email>"
      # the initial password
      #- "PGADMIN_DEFAULT_PASSWORD=<a_secret>"
    volumes:
      - /data/manager-apps/pgadmin4:/var/lib/pgadmin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - proxy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.5
    hostname: phpmyadmin
    networks:
      - proxy
      - backend
    ports:
      - "25111:80" 
    environment:   
      - "PMA_ARBITRARY=1"
      - "PMA_ABSOLUTE_URI=https://terrabrasilis.dpi.inpe.br/phpmyadmin/"
    volumes: 
      - /data/manager-apps/phpmyadmin/sessions:/sessions
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks: 
  proxy:
    external: true
  backend:
    external: true