# The NGINX stack
version: '3.4'
services:

  main_proxy:
    image: nginx:1.22-alpine
    hostname: main.nginx.swarm.proxy
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/log:/var/log/nginx
      - /data/nginx/html:/usr/share/nginx/html
      - /data/nginx/base/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==node1cluster3
      restart_policy:
        condition: on-failure

  download_static_files:
    image: nginx:1.17-alpine
    volumes:
      - /data/download/static:/usr/share/nginx/html:ro
    networks:
      - proxy
    ports:
      - 80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  prodes_dashboard_files_h:
    image: nginx:1.22-alpine
    volumes:
      - /data/homologation/prodes/dashboard/deforestation:/usr/share/nginx/html:ro
    networks:
      - proxy
    ports:
      - 80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
