version: '3.2'
services:
  terrabrasilis-website:
    image: wordpress:5.0.3-apache
    hostname: terrabrasilis.website
    networks:
      - proxy    
    volumes:
      - /data/website:/var/www/html
    ports:
      - 25112:80
    depends_on:
      - db_mysql
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
