# Stack of user register service and control the download file.
# Use in Swarm (prodes_download_controller)
version: '3.1'

services:
  request_file_control:
    image: terrabrasilis/request-file-by-form:v0.1
    hostname: request.file.control
    volumes:
      - /data/download_by_uuid/config:/usr/local/data/config:ro
    secrets:
      - inpe.dpi.mail.user
      - inpe.dpi.mail.pass
      - postgres.user.geoserver
      - postgres.pass.geoserver
    environment:
      SMTP_INPE_MAIL_USER_FILE: /run/secrets/inpe.dpi.mail.user
      SMTP_INPE_MAIL_PASS_FILE: /run/secrets/inpe.dpi.mail.pass
      POSTGRES_USER_FILE: /run/secrets/postgres.user.geoserver
      POSTGRES_PASS_FILE: /run/secrets/postgres.pass.geoserver
      MAIL_FROM_ALIAS: prodes@dpi.inpe.br
    networks:
      - proxy
    ports:
      - "7000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  download_by_uuid:
    image: terrabrasilis/download-by-uuid:v0.1
    hostname: download.by.uuid
    volumes:
      - /data/download_by_uuid/config:/usr/local/data/config:ro
      - /data/download_by_uuid/documents:/usr/local/download-by-uuid/src/documents:ro
    secrets:
      - postgres.user.geoserver
      - postgres.pass.geoserver
    environment:
      FILE_NAME: Prodes2019_amz_incrementos_72cenas.zip
      POSTGRES_USER_FILE: /run/secrets/postgres.user.geoserver
      POSTGRES_PASS_FILE: /run/secrets/postgres.pass.geoserver
    networks:
      - proxy
    ports:
      - "8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  inpe.dpi.mail.user:
    external: true
  inpe.dpi.mail.pass:
    external: true
  postgres.user.geoserver:
    external: true
  postgres.pass.geoserver:
    external: true

networks:
  proxy:
    external: true
