version: '3.2'
services:
  geonetwork:
    image: geonetwork:latest
    restart: always
    networks:
      - proxy
    ports:
      - "8080"
    environment:
      DATA_DIR: /var/lib/geonetwork_data
    volumes:
      - /data/geonetwork:/var/lib/geonetwork_data
      - /data/geonetwork/gn.h2.db:/usr/local/tomcat/webapps/gn.h2.db
      - /data/geonetwork/gn.trace.db:/usr/local/tomcat/webapps/gn.trace.db

networks:
  proxy:
    external: true