version: '3.2'
services:
  geoserver-redd-pac1:
    image: terrabrasilis/geoserver-redd-pac:v1.0
    hostname: geoserver.reddpac
    ports:
      - "8080"
    networks:
      - proxy
    volumes:
      - /data/legacy/geoserver/redd-pac:/data/geoserver/configs
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  geoserver-redd-pac2:
    image: terrabrasilis/geoserver-redd-pac:v1.0
    hostname: geoserver.reddpac
    ports:
      - "8080"
    networks:
      - proxy
    volumes:
      - /data/legacy/geoserver/redd-pac:/data/geoserver/configs
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
