version: '3.2'
services:
    geoserver-master:
      image: terrabrasilis/geoserver:v03
      hostname: geoserver.master
      ports:
        - "10080:8080"
      networks: 
        - proxy
      volumes: 
        - /data/geoserver:/data/geoserver
      tty: true  
      environment:
        - "CATALINA_OPTS=-server \
              -Djava.awt.headless=true \
              -Dfile.encoding=UTF-8 \
              -Xms1024m -Xmx3072m -Xss512m -XX:MaxMetaspaceSize=3072m \
              -XX:+DisableExplicitGC -XX:+UseParallelOldGC \
              -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:+HeapDumpOnOutOfMemoryError"
      deploy:
        replicas: 1
        update_config:
          parallelism: 2
          delay: 10s
        placement:        
          constraints:
            - node.role==manager
        restart_policy:
          condition: on-failure 
    
networks: 
  proxy:
    external: true
