version: '3.2'
services:
    gsbroker:
      image: terrabrasilis/geoserver-broker:v1.0
      hostname: broker.geoserver
      ports:
        - "61666:61666"
        - "8099:8080"
      networks: 
        - geoserverbroker
      volumes:
        - /geoserver/cluster/gs_cluster/gs_datadir:/var/local/geoserver
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure

    gsmaster:
      image: terrabrasilis/geoserver-master:v1.0
      hostname: master.geoserver
      ports:
        - "8888:8080"
      networks:
        - geoserverbroker
        - proxy
      volumes: 
        - /geoserver/cluster/gs_cluster/gs_datadir:/var/local/geoserver
        - /geoserver/cluster/gs_cluster/gs_extensions:/var/local/geoserver-exts
      environment:
        COOKIE: JSESSIONID prefix
        CLUSTER_CONFIG_DIR: /var/local/geoserver/cluster/master
        instanceName: master
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure 

    gsslave1:
      image: terrabrasilis/geoserver-worker:v1.0
      hostname: slave1.geoserver
      networks:
        - geoserverbroker
        - proxy
      volumes:
        - /geoserver/cluster/gs_cluster/gs_datadir:/var/local/geoserver
        - /geoserver/cluster/gs_cluster/gs_extensions:/var/local/geoserver-exts
      environment:
        COOKIE: JSESSIONID prefix
        CLUSTER_CONFIG_DIR: /var/local/geoserver/cluster/slave1
        instanceName: slave1
      ports:
        - "8080"
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure

    gsslave2:
      image: terrabrasilis/geoserver-worker:v1.0
      hostname: slave2.geoserver
      networks:
        - geoserverbroker
        - proxy
      volumes:
        - /geoserver/cluster/gs_cluster/gs_datadir:/var/local/geoserver
        - /geoserver/cluster/gs_cluster/gs_extensions:/var/local/geoserver-exts
      environment:
        COOKIE: JSESSIONID prefix
        CLUSTER_CONFIG_DIR: /var/local/geoserver/cluster/slave2
        instanceName: slave2
      ports:
        - "8080"
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure

networks:
  geoserverbroker:
    external: false
  proxy:
    external: true