## https://www.mundodocker.com.br/tag/docker-stack/
version: '3.2'
services:
  influx:
    image: terrabrasilis/influxdb:v01
    hostname: influx
    networks:
      - metrics
    volumes:
      - /data/influxdb:/var/lib/influxdb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  grafana:
    image: terrabrasilis/grafana:v01
    hostname: grafana
    ports:        
      - "3000:3000"
    networks: 
      - metrics
    volumes: 
      - /data/grafana:/var/lib/grafana
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  agent:
    image: terrabrasilis/cadivisor:v01
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /data-docker:/var/lib/docker:ro
      - /var/run:/var/run
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    entrypoint: "/usr/bin/cadvisor -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086"
    networks:
      - metrics
    deploy:
      mode: global

networks: 
  metrics:
    external: true
  portainer_agent:
    driver: overlay
    attachable: true
