# Use in Swarm
version: '3.2'

services:
  app_survey:
    image: terrabrasilis/survey:v0.3
    ports:
      - "80"
    volumes:
      - /data/survey:/var/www/html
    depends_on:
      - db_mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks: 
      - proxy

  app_certificate:
    image: terrabrasilis/survey:v0.3
    ports:
      - "80"
    volumes:
      - /data/certificado:/var/www/html
    depends_on:
      - db_mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks: 
      - proxy

networks:
  proxy:
    external: true
