version: '3.2'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.5
    hostname: phpmyadmin
    networks:
      - proxy
    ports:
      - "25111:80" 
    environment:   
      - "PMA_ARBITRARY=1"
    volumes: 
      - /data/phpmyadmin/sessions:/sessions
    depends_on:
      - db_mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  proxy:
    external: true
