version: '3.2'
services:
  pgadmin4:
  # https://hub.docker.com/r/dpage/pgadmin4/
  # https://github.com/postgres/pgadmin4
    image: dpage/pgadmin4:5.1
    container_name: pgadmin4
    ports:
      - 5555:80
    volumes:
      - /data/pgclient/pgadmin4:/var/lib/pgadmin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - proxy

networks: 
  proxy:
    external: true