version: '3.2'
services:
  print-project:
    image: wordpress:5.0.3-apache
    #image: wordpress:4.9.8-apache
    hostname: print.project
    networks:
      - proxy    
    volumes:
      - /data/print:/var/www/html
    ports:
      - 25113:80
    depends_on:
      - db_mysql
    deploy:
      replicas: 1      
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true