version: '3.2'
services:
  app_training:
    image: terrabrasilis/treinamento:v0.4
    ports:
      - "80"
    volumes:
      - /data/treinamento:/var/www/html
    depends_on:
      - db_mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks: 
      - proxy

networks: 
  proxy:
    external: true