version: '3.2'
services:
  fipcerrado-website:
    image: wordpress:5.2.2-apache
    hostname: fipcerrado.website
    networks:
      - proxy    
    volumes:
      - /data/wordpress/fipcerrado:/var/www/html
    ports:
      - 25114:80
    depends_on:
      - db_mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  workshop-biomas-2020-website:
    image: wordpress:5.2.2-apache
    hostname: workshop-biomas-2020.website
    networks:
      - proxy
    volumes:
      - /data/wordpress/workshop-biomas-2020:/var/www/html
    ports:
      - 25116:80
    depends_on:
      - db_mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
