# Use in Swarm
version: '3.1'

services:

  db_mysql:
    image: mysql:5.7
    volumes:
      - /data/mysql:/var/lib/mysql
    secrets:
      - server.user.mysql
      - server.pass.mysql
      - server.rootpass.mysql
      - server.dbname.mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/server.rootpass.mysql
      #MYSQL_ROOT_HOST_FILE: /run/secrets/
      MYSQL_DATABASE_FILE: /run/secrets/server.dbname.mysql
      MYSQL_USER_FILE: /run/secrets/server.user.mysql
      MYSQL_PASSWORD_FILE: /run/secrets/server.pass.mysql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.master1==master1
      restart_policy:
        condition: on-failure
    networks: 
      - terrabrasilis
      - proxy

  app_certificates:
    image: terrabrasilis/workshop-certificates:v0.2
    ports:
      - "80"
    depends_on:
      - db_mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks: 
      - terrabrasilis
      - proxy

secrets:
  server.user.mysql:
    external: true
  server.pass.mysql:
    external: true
  server.dbname.mysql:
    external: true
  server.rootpass.mysql:
    external: true

networks: 
  terrabrasilis:
    external: false
  proxy:
    external: true