# Stack of data service and authentication for release DETER data.
# Use in Swarm (deter_release_data)
version: '3.3'

services:
  scripts_generate_files:
    image: terrabrasilis/deter-generate-files:v1.8.10
    hostname: scripts.generate.files
    volumes:
      - /data/deter-auth/generated-files:/data/files
      - /data/deter-auth/logs:/logs
      - /data/deter-auth/to-terrama:/data/terrama/deter-amz
    secrets:
      - geoserver.user.dashboard
      - geoserver.pass.dashboard
      - postgres.user.geoserver
      - postgres.pass.geoserver
      - ftp.user.queimadas
      - ftp.pass.queimadas
    configs:
      - source: ssmtp-tb.conf
        target: /etc/ssmtp/ssmtp.conf
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

  file_delivery_api:
    image: terrabrasilis/file-delivery:v1.0.4
    hostname: file.delivery.auth
    volumes:
      - /data/deter-auth/generated-files:/data/files:ro
      - /data/deter-auth/logs:/logs
    secrets:
      - jwt.private.key
    environment:
      JWT_SECRET: /run/secrets/jwt.private.key
    networks:
      - proxy
    ports:
      - "71:9000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  amz_sync_client:
    image: terrabrasilis/deter-amz-sync-client:v1.8.10
    hostname: amz.sync.client
    volumes:
      - /data/deter-auth/client-api/raw-data:/usr/local/php-client/rawData
      - /data/deter-auth/client-api/log:/usr/local/php-client/log
    secrets:
      - google.mail.user
      - google.mail.pass
      - api.sync.deterb.amz.user
      - api.sync.deterb.amz.pass
      - postgres.user.geoserver
      - postgres.pass.geoserver
    environment:
      SMTP_GOOGLE_MAIL_USER_FILE: /run/secrets/google.mail.user
      SMTP_GOOGLE_MAIL_PASS_FILE: /run/secrets/google.mail.pass
      MAIL_TO: andre.carvalho@inpe.br,alessandra.gomes@inpe.br,adeline.maciel@inpe.br,david.kawamura@inpe.br
      SYNC_SERVICE_USER_FILE: /run/secrets/api.sync.deterb.amz.user
      SYNC_SERVICE_PASS_FILE: /run/secrets/api.sync.deterb.amz.pass
      SYNC_SERVICE_HOST: http://200.18.85.22/
      POSTGRES_USER_FILE: /run/secrets/postgres.user.geoserver
      POSTGRES_PASS_FILE: /run/secrets/postgres.pass.geoserver
      POSTGRES_HOST: 150.163.2.177
      OUTPUT_DATABASE: DETER-B
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

  cerrado_intersection:
    image: terrabrasilis/cerradodeter-syncdata:v1.2.2
    volumes:
      - /data/deter-auth/intersection/cerrado-nb:/usr/local/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  report_news:
    image: terrabrasilis/deter-report:v1.0.1
    volumes:
      - /data/deter-auth/report:/usr/local/data
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - google.mail.user
      - google.mail.pass
      - postgres.user.geoserver
      - postgres.pass.geoserver
    environment:
      MAIL_TO: andre.carvalho@inpe.br,luis.maurano@inpe.br,claudio.almeida@inpe.br,alessandra.gomes@inpe.br,adeline.maciel@inpe.br,david.kawamura@inpe.br,marcos.adami@inpe.br
      SMTP_GOOGLE_MAIL_USER_FILE: /run/secrets/google.mail.user
      SMTP_GOOGLE_MAIL_PASS_FILE: /run/secrets/google.mail.pass
      POSTGRES_USER_FILE: /run/secrets/postgres.user.geoserver
      POSTGRES_PASS_FILE: /run/secrets/postgres.pass.geoserver
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  daily_deter_for_ibama:
    image: terrabrasilis/daily-deter-for-ibama:v1.2.5
    hostname: daily.deter.for.ibama
    volumes:
      - /data/deter-auth/deter-ibama:/data/files
      - /data/deter-auth/logs:/logs
    secrets:
      - postgres.port.deter_r
      - postgres.db.deter_r
      - postgres.host.deter_r
      - postgres.user.deter_r
      - postgres.pass.deter_r
      - postgres.table.deter_r
      - postgres.schema.deter_r
      - ftp.user.censipam
      - ftp.pass.censipam
      - ftp.host.censipam
      - ftp.path.censipam
      - www1.ecdsa.private.key
      - www1.user.scp
      - www1.path.scp
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

configs:
  ssmtp-tb.conf:
    external: true

secrets:
  www1.ecdsa.private.key:
    external: true
  www1.user.scp:
    external: true
  www1.path.scp:
    external: true
  postgres.port.deter_r:
    external: true
  postgres.db.deter_r:
    external: true
  postgres.host.deter_r:
    external: true
  postgres.user.deter_r:
    external: true
  postgres.pass.deter_r:
    external: true
  postgres.table.deter_r:
    external: true
  postgres.schema.deter_r:
    external: true
  ftp.user.censipam:
    external: true
  ftp.pass.censipam:
    external: true
  ftp.host.censipam:
    external: true
  ftp.path.censipam:
    external: true
  google.mail.user:
    external: true
  google.mail.pass:
    external: true
  api.sync.deterb.amz.user:
    external: true
  api.sync.deterb.amz.pass:
    external: true
  postgres.user.geoserver:
    external: true
  postgres.pass.geoserver:
    external: true
  geoserver.user.dashboard:
    external: true
  geoserver.pass.dashboard:
    external: true
  jwt.private.key:
    external: true
  ftp.user.queimadas:
    external: true
  ftp.pass.queimadas:
    external: true

networks:
  proxy:
    external: true
