# Stack of a file provider user validator 
# Use in Swarm 
version: '3.1'

services:

  file_delivery_api_homologation:
    image: terrabrasilis/file-delivery:v1.0.1
    hostname: file.delivery.auth
    volumes:
      - /data/deter-auth/generated-files:/data/files:ro
      - /data/deter-auth/logs:/logs
    secrets:
      - jwt.private.key
    environment:
      JWT_SECRET: /run/secrets/jwt.private.key
    networks:
      - proxy
    ports:
      - "9000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  jwt.private.key:
    external: true

networks:
  proxy:
    external: true
