# Stack of data service and authentication for release DETER data.
# Use in Swarm (deter_release_data)
version: '3.1'

services:
  

  terrabrasilis_oauth_api:
    image: terrabrasilis/terrabrasilis-oauth-api:v1.0.2
    hostname: oauth.api
    volumes:
      - /data/oauth-api/logs:/logs
    secrets:
      - jwt.private.key
    environment:
      JWT_SECRET: /run/secrets/jwt.private.key
    networks:
      - proxy
    ports:
      - "9000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  jwt.private.key:
    external: true

networks:
  proxy:
    external: true
