version: '3.2'
services:

  # frontend app
  situacao-atual:
    image: terrabrasilis/queimadas-situacao-atual:v1.1.2
    ports:
      - "80"
    networks:
      - proxy
    volumes:
      - /data/apps/media:/var/www/html/media
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  # backend service
  situacao-atual-gerador:
    image: terrabrasilis/queimadas-situacao-atual-gerador:v1.0.0
    networks:
      - proxy
    volumes:
      - /data/apps/media:/app/media
      - /data/apps/gerador/config.ini:/app/config.ini
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
