version: '3.2'
services:

  situacao-atual:
    image: terrabrasilis/queimadas-situacao-atual:v1.1.0
    ports:
      - "80"
    networks:
      - proxy
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
