version: '3.2'
services:

  # backend service
  situacao-atual-gerador:
    image: terrabrasilis/queimadas-situacao-atual-gerador:v1.1.1
    networks:
      - proxy
    volumes:
      - /data/apps/media:/app/media
      - /data/apps/gerador/config.ini:/app/config.ini
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
