version: '3.2'
services:

  # frontend app
  situacao-atual:
    image: terrabrasilis/queimadas-situacao-atual:v1.1.2
    ports:
      - "80"
    networks:
      - proxy
    volumes:
      - /data/apps/media:/var/www/html/media
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
