#geoserver-cluster

version: '3.2'
services:
    gsmaster:
      image: terrabrasilis/geoserver-master:v1.0.6
      hostname: master.geoserver
      ports:
        - "30000:8080"
      networks:
        - proxy
      extra_hosts:
        - "pg13queimadas:192.168.1.17"
      volumes:
        - /geoserver/cluster/gs_datadir:/var/local/geoserver
        - /geoserver/cluster/gs_extensions:/var/local/geoserver-exts
      environment:
        GEOSERVER_CSRF_DISABLED: "true"
        COOKIE: JSESSIONID prefix
        CLUSTER_CONFIG_DIR: /var/local/geoserver/cluster/master
        GEOSERVER_LOG_LOCATION: /var/local/geoserver/cluster/logs/master
        CATALINA_OPTS: -XX:OnOutOfMemoryError="kill -9 %p" -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms1024m -Xmx3072m -Xss1024k -XX:NewSize=768m -XX:+UseParallelGC -XX:MaxGCPauseMillis=500 -DGEOSERVER_DATA_DIR=/var/local/geoserver
        instanceName: master
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure 

    gsslave1:
      image: terrabrasilis/geoserver-worker:v1.0.6
      hostname: slave1.geoserver
      networks:
        - proxy
      extra_hosts:
        - "pg13queimadas:192.168.1.17"
      volumes:
        - /geoserver/cluster/gs_datadir:/var/local/geoserver
        - /geoserver/cluster/gs_extensions:/var/local/geoserver-exts
      environment:
        GEOSERVER_CSRF_DISABLED: "true"
        COOKIE: JSESSIONID prefix
        CLUSTER_CONFIG_DIR: /var/local/geoserver/cluster/slave1
        GEOSERVER_LOG_LOCATION: /var/local/geoserver/cluster/logs/slave1
        CATALINA_OPTS: -XX:OnOutOfMemoryError="kill -9 %p" -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms1024m -Xmx3072m -Xss1024k -XX:NewSize=768m -XX:+UseParallelGC -XX:MaxGCPauseMillis=500 -DGEOSERVER_DATA_DIR=/var/local/geoserver
        instanceName: slave1
      ports:
        - "30010:8080"
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure

    gsslave2:
      image: terrabrasilis/geoserver-worker:v1.0.6
      hostname: slave2.geoserver
      networks:
        - proxy
      extra_hosts:
        - "pg13queimadas:192.168.1.17"
      volumes:
        - /geoserver/cluster/gs_datadir:/var/local/geoserver
        - /geoserver/cluster/gs_extensions:/var/local/geoserver-exts
      environment:
        GEOSERVER_CSRF_DISABLED: "true"
        COOKIE: JSESSIONID prefix
        CLUSTER_CONFIG_DIR: /var/local/geoserver/cluster/slave2
        GEOSERVER_LOG_LOCATION: /var/local/geoserver/cluster/logs/slave2
        CATALINA_OPTS: -XX:OnOutOfMemoryError="kill -9 %p" -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms1024m -Xmx3072m -Xss1024k -XX:NewSize=768m -XX:+UseParallelGC -XX:MaxGCPauseMillis=500 -DGEOSERVER_DATA_DIR=/var/local/geoserver
        instanceName: slave2
      ports:
        - "30020:8080"
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure

    gsslave3:
      image: terrabrasilis/geoserver-worker:v1.0.6
      hostname: slave3.geoserver
      networks:
        - proxy
      extra_hosts:
        - "pg13queimadas:192.168.1.17"
      volumes:
        - /geoserver/cluster/gs_datadir:/var/local/geoserver
        - /geoserver/cluster/gs_extensions:/var/local/geoserver-exts
      environment:
        GEOSERVER_CSRF_DISABLED: "true"
        COOKIE: JSESSIONID prefix
        CLUSTER_CONFIG_DIR: /var/local/geoserver/cluster/slave3
        GEOSERVER_LOG_LOCATION: /var/local/geoserver/cluster/logs/slave3
        CATALINA_OPTS: -XX:OnOutOfMemoryError="kill -9 %p" -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms1024m -Xmx3072m -Xss1024k -XX:NewSize=768m -XX:+UseParallelGC -XX:MaxGCPauseMillis=500 -DGEOSERVER_DATA_DIR=/var/local/geoserver
        instanceName: slave3
      ports:
        - "30030:8080"
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure

    gsslave4:
      image: terrabrasilis/geoserver-worker:v1.0.6
      hostname: slave4.geoserver
      networks:
        - proxy
      extra_hosts:
        - "pg13queimadas:192.168.1.17"
      volumes:
        - /geoserver/cluster/gs_datadir:/var/local/geoserver
        - /geoserver/cluster/gs_extensions:/var/local/geoserver-exts
      environment:
        GEOSERVER_CSRF_DISABLED: "true"
        COOKIE: JSESSIONID prefix
        CLUSTER_CONFIG_DIR: /var/local/geoserver/cluster/slave4
        GEOSERVER_LOG_LOCATION: /var/local/geoserver/cluster/logs/slave4
        CATALINA_OPTS: -XX:OnOutOfMemoryError="kill -9 %p" -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms1024m -Xmx3072m -Xss1024k -XX:NewSize=768m -XX:+UseParallelGC -XX:MaxGCPauseMillis=500 -DGEOSERVER_DATA_DIR=/var/local/geoserver
        instanceName: slave4
      ports:
        - "30040:8080"
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure

networks:
  proxy:
    external: true
