# ogc-services

version: '3.4'
services:
  geoserver-master:
    image: kartoza/geoserver:2.25.2
    hostname: geoserver-master
    ports:
      - "3100:8080"
    networks:
      - proxy
    extra_hosts:
        - "pg13queimadas:192.168.1.17"
    volumes:
      - /geoserver/2_25_2/gs_datadir:/var/local/geoserver
      - /geoserver/2_25_2/gs_gwc:/var/local/geoserver_gwc
    environment:
      GEOSERVER_DATA_DIR: /var/local/geoserver
      GEOSERVER_CONTEXT_ROOT: queimadas#geoserver
      GEOSERVER_LOG_PROFILE: PRODUCTION_LOGGING
      GEOSERVER_LOG_DIR: /var/local/geoserver/cluster/master/logs
      GEOSERVER_LOG_LOCATION: /var/local/geoserver/cluster/master/logs/geoserver.log
      CLUSTER_CONFIG_DIR: /var/local/geoserver/cluster/master
      GEOWEBCACHE_CACHE_DIR: /var/local/geoserver/gwc/
      instanceName: master
      GEOSERVER_PORT: 8080
      CLUSTERING: 'False'
      EXISTING_DATA_DIR: 'true'
      ENABLE_JSONP: 'false'
      # JVM options
      INITIAL_MEMORY: 1G
      # https://docs.geoserver.org/stable/en/user/production/container.html#optimize-your-jvm
      MAXIMUM_MEMORY: 2G
      INITIAL_HEAP_OCCUPANCY_PERCENT: 45
      # JVM Startup option for encoding
      ENCODING: 'UTF8'
      # JVM Startup option for timezone
      TIMEZONE: 'GMT'
      # Additional JVM startup options not specified in https://github.com/kartoza/docker-geoserver/blob/master/scripts/entrypoint.sh#L21
      # Example ADDITIONAL_JAVA_STARTUP_OPTIONS='-Dorg.geotools.shapefile.datetime=true'
      # ADDITIONAL_JAVA_STARTUP_OPTIONS: -XX:OnOutOfMemoryError="kill -9 %p"
      ADDITIONAL_JAVA_STARTUP_OPTIONS: -XX:+ExitOnOutOfMemoryError
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==node1cluster3
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true