version: '3.2'
services:

  fires-data-task:
    image: terrabrasilis/fires-data-task-release-1:v1.3.9
    volumes:
      - /data/fires/input/raster:/usr/local/data
      - /data/download/static/fires-dashboard/deter/raster:/usr/local/download
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
