version: '3.2'
services:
  pg11_postgis2_5_fm:
    image: terrabrasilis/postgis-shp2pgsql:11-2.5
    hostname: forestmonitor.postgis
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER_FILE: /run/secrets/server.user.postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/server.pass.postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    secrets:
      - server.user.postgres
      - server.pass.postgres
    volumes:
      - /data/cluster2/fm/postgres/pgdata:/var/lib/postgresql/data/pgdata
      - /data/cluster2/fm/postgres/scripts:/scripts
    deploy:
      replicas: 1
      placement:
        constraints:
          # keeping instance in node3 to access disk data direct without NFS tier
          - node.labels.nodename==node3.master.cluster2
      restart_policy:
        condition: on-failure
    networks:
      - proxy

secrets:
  server.user.postgres:
    external: true
  server.pass.postgres:
    external: true

networks:
  proxy:
    external: true
