services:

  # The instance of API to PRODES appeals system
  sicar-prodes-api-h:
    image: terrabrasilis/sicar-appeals-analysis-api:v1.0.0
    secrets:
      - prodes.pantanal.database.url
      - prodes.amazonia.database.url
      - prodes.cerrado.database.url
      - prodes.pampa.database.url
      - prodes.caatinga.database.url
      - prodes.mata_atlantica.database.url
      - sicar.database.url
    environment:
      - "DB_URL_PANTANAL=/run/secrets/prodes.pantanal.database.url"
      - "DB_URL_AMAZONIA=/run/secrets/prodes.amazonia.database.url"
      - "DB_URL_CERRADO=/run/secrets/prodes.cerrado.database.url"
      - "DB_URL_PAMPA=/run/secrets/prodes.pampa.database.url"
      - "DB_URL_CAATINGA=/run/secrets/prodes.caatinga.database.url"
      - "DB_URL_MATA_ATLANTICA=/run/secrets/prodes.mata_atlantica.database.url"
      - "DB_URL_SICAR=/run/secrets/sicar.database.url"
      - "SCRIPT_NAME=/sicar-prodes-api/"
    networks:
      - proxy
    ports:
      - "8001:8001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  prodes.pantanal.database.url:
    external: true
  prodes.amazonia.database.url:
    external: true
  prodes.cerrado.database.url:
    external: true
  prodes.pampa.database.url:
    external: true
  prodes.caatinga.database.url:
    external: true
  prodes.mata_atlantica.database.url:
    external: true
  sicar.database.url:
    external: true

networks:
  proxy:
    external: true