# Use in Swarm (apis)
version: '3.4'
services:

  # Business API as a Service
  business-api:
    image: terrabrasilis/business-api:v1.2.4
    networks:
      - proxy
      - backend
    ports:
      - "8090"
    environment:   
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "httpcode=`curl -s -o /dev/null --head -w \"%{http_code}\" -X GET \"http://localhost:8090/api/v1/layer/health\"`; if [ ! $httpcode = \"200\" ]; then exit 1; fi"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 20s

  # File delivery service API with authentication
  file_delivery_api:
    image: terrabrasilis/file-delivery:v1.0.6
    hostname: file.delivery.auth
    volumes:
      - /data/deter-auth/generated-files:/data/files:ro
      - /data/deter-auth/logs:/logs
    secrets:
      - jwt.private.key
    environment:
      JWT_SECRET: /run/secrets/jwt.private.key
      OAUTH_API_URL: "https://terrabrasilis.dpi.inpe.br/oauth-api/"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    networks:
      - proxy
    ports:
      - "9000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "httpcode=`curl -s -o /dev/null --head -w \"%{http_code}\" -X GET \"http://localhost:9000/health\"`; if [ ! $httpcode = \"200\" ]; then exit 1; fi"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 20s
        
  # Middleware authentication service
  oauth_api:
    image: terrabrasilis/terrabrasilis-oauth-api:v1.3.5
    hostname: oauth.api
    volumes:
      - /data/oauth-api/logs:/logs
      - /data/oauth-api/config:/data/oauth-api/config
    secrets:
      - jwt.private.key
    environment:
      JWT_SECRET: /run/secrets/jwt.private.key
      PROXY_CONFIG_FILE: /data/oauth-api/config/proxy_config.json
    networks:
      - proxy
    ports:
      - "9000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "httpcode=`curl -s -o /dev/null --head -w \"%{http_code}\" -X GET \"http://localhost:9000/health\"`; if [ ! $httpcode = \"200\" ]; then exit 1; fi"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 20s

secrets:
  jwt.private.key:
    external: true

networks:
  proxy:
    external: true
  backend:
    external: true
