# Use in Swarm (background_tasks)
version: '3.4'

services:
  # export DETER data to shp and json files, among other things
  generate_files:
    image: terrabrasilis/deter-generate-files:v2.2.2
    hostname: generate.files
    volumes:
      - /data/deter-auth/generated-files:/data/files
      - /data/deter-auth/logs:/logs
      - /data/deter-auth/to-terrama:/data/terrama/deter-amz
    secrets:
      - geoserver.user.dashboard
      - geoserver.pass.dashboard
      - postgres.user.geoserver
      - postgres.pass.geoserver
      - postgres.user.prod
      - postgres.pass.prod
      - ftp.user.queimadas
      - ftp.pass.queimadas
    configs:
      - source: ssmtp-tb.conf
        target: /etc/ssmtp/ssmtp.conf
      - source: deter-etc-environment
        target: /etc/environment
    networks:
      - backgroundtask
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  deter_amz_sync:
    image: terrabrasilis/deter-amz-sync-client:v1.8.10
    hostname: amz.sync.client
    volumes:
      - /data/deter-auth/client-api/raw-data:/usr/local/php-client/rawData
      - /data/deter-auth/client-api/log:/usr/local/php-client/log
    secrets:
      - google.mail.user
      - google.mail.pass
      - api.sync.deterb.amz.user
      - api.sync.deterb.amz.pass
      - postgres.user.geoserver
      - postgres.pass.geoserver
    environment:
      SMTP_GOOGLE_MAIL_USER_FILE: /run/secrets/google.mail.user
      SMTP_GOOGLE_MAIL_PASS_FILE: /run/secrets/google.mail.pass
      MAIL_TO: afa.decarvalho@gmail.com
      SYNC_SERVICE_USER_FILE: /run/secrets/api.sync.deterb.amz.user
      SYNC_SERVICE_PASS_FILE: /run/secrets/api.sync.deterb.amz.pass
      SYNC_SERVICE_HOST: http://150.163.54.22/
      POSTGRES_USER_FILE: /run/secrets/postgres.user.geoserver
      POSTGRES_PASS_FILE: /run/secrets/postgres.pass.geoserver
      POSTGRES_HOST: 192.168.1.17
      OUTPUT_DATABASE: deter_amazonia_nb
    networks:
      - backgroundtask
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  deter_cerrado_sync:
    image: terrabrasilis/cerradodeter-syncdata:v1.5.0
    volumes:
      - /data/deter-auth/intersection/cerrado-nb:/usr/local/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backgroundtask
    environment:
      AUDITED_DATE: '2025-08-01'
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  # verify DETER amz data and send a report by email
  deter_report_amz:
    image: terrabrasilis/deter-report:v1.0.1
    volumes:
      - /data/deter-auth/report:/usr/local/data
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - google.mail.user
      - google.mail.pass
      - postgres.user.geoserver
      - postgres.pass.geoserver
    environment:
      MAIL_TO: afa.decarvalho@gmail.com
      SMTP_GOOGLE_MAIL_USER_FILE: /run/secrets/google.mail.user
      SMTP_GOOGLE_MAIL_PASS_FILE: /run/secrets/google.mail.pass
      POSTGRES_USER_FILE: /run/secrets/postgres.user.geoserver
      POSTGRES_PASS_FILE: /run/secrets/postgres.pass.geoserver
    networks:
      - backgroundtask
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  # Queimadas database update task within the TerraBrasilis infrastructure
  general-fires-data-task:
    image: terrabrasilis/general-fires-data-task-main:v2.0.0
    hostname: fires.sync
    volumes:
      - /data/fires/sync:/usr/local/data
    environment:
      GEOSERVER_BASE_URL: https://terrabrasilis.dpi.inpe.br
      GEOSERVER_BASE_PATH: queimadas/geoserver
    networks:
      - backgroundtask
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  # to update dashboard-fires database statistics
  dashboard-fires-data-task:
    image: terrabrasilis/fires-data-task-all-biomes:v1.5.3
    volumes:
      - /data/fires-task:/usr/local/data
    environment:
      DETER_VIEW_DATE: '2023-08-01'
    networks:
      - backgroundtask
    deploy:
      replicas: 1
      placement:
        constraints:
          # force the service on node5 because its has more memory than others
          - node.hostname==node5
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  # to generate the cloud cover using cmask data for DETER Cerrado and Amazonia
  cmask-data-task:
    image: 'terrabrasilis/deter-cmask-data-task:v1.0.13'
    hostname: cmask.data.task
    volumes:
      - '/data/deter-task/cmask:/usr/local/data'
      - '/data/download/static/cmask:/usr/local/download/static/cmask'
    environment:
      - "FORCE_YEAR_MONTH=no"
      - "EVERY_DAY=no"
      - "BASE_URL=http://150.163.2.139:8089/files"
      - "FORCE_REBUILD=no"
      - "START_YEAR_MONTH=2024-01"
      - "END_YEAR_MONTH=2025-05"
    deploy:
      replicas: 1
      placement:
        constraints:
          # force the service on node5 node because its has more memory than others
          - node.hostname==node5
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  # Amazon Biome Database Update Task for AMS Application
  ams-sync-amazonia:
    image: terrabrasilis/ams-sync:v2.2.4
    hostname: ams.amazonia.sync
    volumes:
      - /data/ams-task/amazonia/sync:/usr/local/data
    environment:
      - "BIOME=Amazônia"
      - "INPUT_GEOTIFF_FUNDIARY_STRUCTURE=estrutura_fundiaria_cst_2023.tif"
      - "DATABASE_URL=/run/secrets/ams.database.url.amz.v2"
      - "ALL_DATA=True"
      - "FTP_HOST=/run/secrets/risk.ftp.host"
      - "FTP_PORT=/run/secrets/risk.ftp.port"
      - "FTP_PATH=/run/secrets/risk.ftp.path"
      - "FTP_USER=/run/secrets/risk.ftp.user"
      - "FTP_PASS=/run/secrets/risk.ftp.pass"
      - "RISK_OUTPUT_PATH=/usr/local/data"
    secrets:
      - ams.database.url.amz.v2
      - risk.ftp.host
      - risk.ftp.port
      - risk.ftp.path
      - risk.ftp.user
      - risk.ftp.pass
    networks:
      - backgroundtask
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  # Cerrado Biome Database Update Task for AMS Application
  ams-sync-cerrado:
    image: terrabrasilis/ams-sync:v2.2.4
    hostname: ams.cerrado.sync
    volumes:
      - /data/ams-task/cerrado/sync:/usr/local/data
    environment:
      - "BIOME=Cerrado"
      - "INPUT_GEOTIFF_FUNDIARY_STRUCTURE=estrutura_fundiaria_cerrado_cst_lzw.tif"
      - "DATABASE_URL=/run/secrets/ams.database.url.cer.v2"
      - "ALL_DATA=True"
    secrets:
      - ams.database.url.cer.v2
    networks:
      - backgroundtask
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

# configuration files in Portainer
configs:
  ssmtp-tb.conf:
    external: true
  deter-etc-environment:
    external: true

secrets:
  google.mail.user:
    external: true
  google.mail.pass:
    external: true
  api.sync.deterb.amz.user:
    external: true
  api.sync.deterb.amz.pass:
    external: true
  postgres.user.geoserver:
    external: true
  postgres.pass.geoserver:
    external: true
  geoserver.user.dashboard:
    external: true
  geoserver.pass.dashboard:
    external: true
  ftp.user.queimadas:
    external: true
  ftp.pass.queimadas:
    external: true
  postgres.user.prod:
    external: true
  postgres.pass.prod:
    external: true
  ams.database.url.amz.v2:
    external: true
  ams.database.url.cer.v2:
    external: true
  risk.ftp.host:
    external: true
  risk.ftp.port:
    external: true
  risk.ftp.path:
    external: true
  risk.ftp.user:
    external: true
  risk.ftp.pass:
    external: true

networks:
  backgroundtask:
    external: false
