# Used for deploy manager-apps stack
version: '3.4'

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.5
    hostname: phpmyadmin
    networks:
      - proxy
      - backend
    ports:
      - "25111:80" 
    environment:   
      - "PMA_ARBITRARY=1"
      - "PMA_ABSOLUTE_URI=https://pve12.dpi.inpe.br/phpmyadmin/"
    volumes: 
      - /data/manager-apps/phpmyadmin/sessions:/sessions
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

networks: 
  proxy:
    external: true
  backend:
    external: true
