# Used for deploy homologation Apps
version: '3.4'

services:

  deforestation-dashboard-h:
    image: terrabrasilis/deforestation-dashboard:hom_v3.4.6
    networks:
      - proxy
    ports:
      - "80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "httpcode=`curl -s -o /dev/null --head -w \"%{http_code}\" -X GET \"http://localhost\"`; if [ ! $httpcode = \"200\" ]; then exit 1; fi"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s

  amsh-webapp:
    image: terrabrasilis/ams-webapp:v3.0.3.homologation.rc
    hostname: amsh.webapp
    entrypoint: /docker-entrypoint.sh
    networks:
      - proxy
    ports:
      - 7000
    environment:
      - "SCRIPT_NAME=/ams-homologation"
      - "GEOSERVER_URL=https://terrabrasilis.dpi.inpe.br/geoserver"
      - "SERVER_NAME=terrabrasilis.dpi.inpe.br"
      - "APPLICATION_ROOT=/ams-homologation/"
      - "DB_URL=/run/secrets/amsh.database.url.v3"
    secrets:
      - amsh.database.url.v3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  amsh.database.url.v3:
    external: true

networks:
  proxy:
    external: true
