# Used for deploy webservers stack
version: '3.4'

services:

  main_proxy:
    image: nginx:1.22-alpine
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/log:/var/log/nginx
      - /data/nginx/html:/usr/share/nginx/html
      - /data/nginx/base/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==node1
      restart_policy:
        condition: any
        delay: 5s
        window: 120s

  download_static_files:
    image: nginx:1.22-alpine
    volumes:
      - /data/download/static:/usr/share/nginx/html:ro
    networks:
      - proxy
    ports:
      - 80
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  prodes_dashboard_files:
    image: nginx:1.22-alpine
    volumes:
      - /data/prodes/dashboard/deforestation:/usr/share/nginx/html:ro
    networks:
      - proxy
    ports:
      - 80
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  risk_stac_files:
    image: nginx:1.27-alpine
    volumes:
      - /data/risk-stac-api/risk:/usr/share/nginx/html:ro
    networks:
      - proxy
    ports:
      - 80
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  proxy:
    external: true
