# Used for deploy webservers-homologation stack
version: '3.4'

services:

  prodes-dashboard-files-h:
    image: nginx:1.22-alpine
    volumes:
      - /data/homologation/prodes/dashboard/deforestation:/usr/share/nginx/html:ro
    networks:
      - proxy
    ports:
      - 80
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  proxy:
    external: true
