# Used for deploy manager-apps stack
version: '3.4'

services:

  pgadmin4:
  # https://hub.docker.com/r/dpage/pgadmin4/
  # https://github.com/postgres/pgadmin4
    image: dpage/pgadmin4:8.12
    ports:
      - 5555:80
    networks:
      - proxy
    #environment:
      # after starting for the first time, use the web app to change this password
      # and then remove these entries.
      # the initial email
      #- "PGADMIN_DEFAULT_EMAIL=<an_email>"
      # the initial password
      #- "PGADMIN_DEFAULT_PASSWORD=<a_secret>"
    volumes:
      - /main/ears/manager-apps/pgadmin4:/var/lib/pgadmin
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

networks: 
  proxy:
    external: true
