version: '3.4'

services:

  geoserver-analyzer:
    image: terrabrasilis/geoserver-analyzer:v1.0.0
    networks:
      - proxy
    volumes:
      - /data/manager-apps/geoserver-analyzer/output/:/usr/local/geoserver-analyzer/output/
    environment:      
      GEOSERVER_USERNAME_FILE: /run/secrets/geoserver.admin.user
      GEOSERVER_PASSWORD_FILE: /run/secrets/geoserver.admin.password
      BUSINESS_API_URL: "https://pve12.dpi.inpe.br/business/api/v1/vision/name/deforestation/all;https://pve12.dpi.inpe.br/business/api/v1/vision/name/alerts/all;https://pve12.dpi.inpe.br/business/api/v1/vision/name/vegetation/all"
      GEOSERVER_URL: "https://pve12.dpi.inpe.br/geoserver/"    
    secrets:
      - geoserver.admin.user
      - geoserver.admin.password
    deploy:
      replicas: 1
      restart_policy:
        condition: none