version: '3.2'
services:
  node3-check:
    image: terrabrasilis/cluster-check:v0.1
    hostname: node3-check
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nodename==node3.master.cluster2
      restart_policy:
        condition: on-failure
        
  node2-check:
    image: terrabrasilis/cluster-check:v0.1
    hostname: node2-check
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nodename==node2.cluster2
      restart_policy:
        condition: on-failure

  node1-check:
    image: terrabrasilis/cluster-check:v0.1
    hostname: node1-check
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nodename==node1.cluster2
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true