version: '3.2'

services:

  deter-sar:
    image: terrabrasilis/deter-sar-ftp-download:v0.1.3
    volumes:
      - /data/deter-sar/download-sar-ftp:/usr/local/data
    secrets:
      - forest-monitor-postgis.user.postgres
      - forest-monitor-postgis.pass.postgres
      - ftp.dpi.user
      - ftp.dpi.pass
    environment:
      FTP_USER: /run/secrets/ftp.dpi.user
      FTP_PASS: /run/secrets/ftp.dpi.pass
      POSTGRES_USER_FILE: /run/secrets/forest-monitor-postgis.user.postgres
      POSTGRES_PASS_FILE: /run/secrets/forest-monitor-postgis.pass.postgres
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nodename==node3.master.cluster2
      restart_policy:
        condition: on-failure

secrets:
  forest-monitor-postgis.user.postgres:
    external: true
  forest-monitor-postgis.pass.postgres:
    external: true
  ftp.dpi.user:
    external: true
  ftp.dpi.pass:
    external: true

networks:
  proxy:
    external: true
