# The NGINX stack for cluster2
version: '3.2'
services:
  cluster2-nginx:
    image: terrabrasilis/nginx-manager:v1.0
    hostname: cluster2.nginx
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /data/cluster2/nginx/conf.d:/etc/nginx/conf.d
      - /data/cluster2/nginx/log:/var/log/nginx
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nodename==node3.master.cluster2
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
