version: '2'

services:
  geoserver-local:
    image: terrabrasilis/geoserver-deter:v1.0.0
    hostname: master.geoserver
    ports:
      - "80:8080"
    volumes:
      - /home/andre/Dados/tmp/geoserver/gs_datadir:/var/local/geoserver
      - /home/andre/Dados/tmp/geoserver/gs_extensions:/var/local/geoserver-exts
      - /home/andre/Dados/tmp/geoserver/data/production:/var/local/geoserver/data-files:ro
    environment:
      COOKIE: JSESSIONID prefix
      CLUSTER_CONFIG_DIR: /var/local/geoserver/cluster/master
      GEOSERVER_LOG_LOCATION: /var/local/geoserver/cluster/logs/master
      instanceName: master
    restart: always