version: '3.2'
services:

  ### Business API as a Service
  business-api-homologation:
    image: terrabrasilis/business-api:v1.0
    hostname: "business.api.homologation"
    networks:
      - proxy
    ports:
      - "13111:8090"
    environment:   
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - mongodbhomologation
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

  # The instance of MongoDB to store the BusinessAPI documents
  mongodbhomologation:
    image: mongo:4
    hostname: "mongo.homologation"
    networks:
      - proxy
    secrets:
      - mongo.user.businessapi
      - mongo.pass.businessapi
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo.user.businessapi
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo.pass.businessapi
    volumes:
      - /data/mongodb-homologation:/data/db
    ports:
      - "30043:27017"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure
    command: mongod --smallfiles --logpath=/dev/null # --quiet
        
secrets:
  mongo.user.businessapi:
    external: true
  mongo.pass.businessapi:
    external: true

networks:
  proxy:
    external: true