version: '3.2'
services:

  ### Business API as a Service
  business-api:
    image: terrabrasilis/business-api:v1.2.2
    hostname: "business.api"
    networks:
      - proxy
    ports:
      - "13222:8090"
    environment:   
      - "SPRING_PROFILES_ACTIVE=docker"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8090/api/v1/download/all || exit 1"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # The instance of MongoDB to store the BusinessAPI documents
  mongodb:
    image: mongo:4.4
    hostname: "mongo.db"
    networks:
      - proxy
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - /data/mongodb:/data/db
    ports:
      - "30046:27017"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.getMongo()' | mongo --norc --quiet --host=localhost:27017 || exit 1"]
      interval: 1m10s
      timeout: 5s
      retries: 3

networks:
  proxy:
    external: true
