# business-api-h
version: '3.2'
services:

  # Business API as a Service
  business-api-homologation:
    image: terrabrasilis/business-api:v1.2.2
    hostname: "business.api.homologation"
    networks:
      - proxy
    ports:
      - "13111:8090"
    environment:   
      - "SPRING_PROFILES_ACTIVE=docker-homologation"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8090/api/v1/download/all || exit 1"]

  # The instance of MongoDB to store the BusinessAPI documents
  mongodbhomologation:
    image: mongo:4.4
    hostname: "mongo.homologation"
    networks:
      - proxy
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - /data/mongodb-homologation:/data/db
    ports:
      - "30043:27017"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.getMongo()' | mongo --norc --quiet --host=localhost:27017 || exit 1"]
      interval: 1m10s
      timeout: 5s
      retries: 3

networks:
  proxy:
    external: true
