version: '3.2'
services:

  ### Business API as a Service
  business-api-homologation:
    image: terrabrasilis/business-api:v1.2.1
    hostname: "business.api.homologation"
    networks:
      - proxy
    ports:
      - "13111:8090"
    environment:   
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - mongodbhomologation
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # The instance of MongoDB to store the BusinessAPI documents
  mongodbhomologation:
    image: mongo:4
    hostname: "mongo.homologation"
    networks:
      - proxy
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - /data/mongodb-homologation:/data/db
    ports:
      - "30043:27017"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
